import Foundation

/// The canonical copy keys on iOS (`IC-017`, `DEC-144`): one case per key of the shared `CopyKeys`,
/// whose raw value is the key name the resource files carry.
///
/// A screen names a key through a case and never types it, so a typo is a compile error rather than
/// the key showing on screen. `TEST-UNIT-097` holds the cases to `CopyKeys.all` in both directions, so
/// a key added on one side only fails the suite. Plural keys stay in `CopyKeys.plurals`.
public enum CopyKey: String, CaseIterable, Sendable {
    case errorTitle = "error_title"
    case actionRetry = "action_retry"
    case stateStaleBanner = "state_stale_banner"
    case emptySearchMessage = "empty_search_message"
    case actionClearFilters = "action_clear_filters"
    case actionBack = "action_back"
    case errorMessageOffline = "error_message_offline"
    case errorMessageTimeout = "error_message_timeout"
    case errorMessageNotFound = "error_message_not_found"
    case errorMessageInvalidRequest = "error_message_invalid_request"
    case errorMessageRateLimited = "error_message_rate_limited"
    case errorMessageRateLimitedNoCountdown = "error_message_rate_limited_no_countdown"
    case errorMessageServer = "error_message_server"
    case errorMessageGraphql = "error_message_graphql"
    case errorMessageMalformed = "error_message_malformed"
    case errorMessageEmptyBody = "error_message_empty_body"
    case errorMessageUnknown = "error_message_unknown"
    case detailErrorInline = "detail_error_inline"
    case statusAlive = "status_alive"
    case statusDead = "status_dead"
    case valueUnknown = "value_unknown"
    case statusAnnouncement = "status_announcement"
    case genderFemale = "gender_female"
    case genderMale = "gender_male"
    case genderGenderless = "gender_genderless"
    case appName = "app_name"
    case splashWordmark = "splash_wordmark"
    case splashWordmarkSub = "splash_wordmark_sub"
    case splashTagline = "splash_tagline"
    case splashLoading = "splash_loading"
    case navCharacters = "nav_characters"
    case navEpisodes = "nav_episodes"
    case navFavorites = "nav_favorites"
    case navSettings = "nav_settings"
    case episodesHeading = "episodes_heading"
    case episodesBody = "episodes_body"
    case favoritesHeading = "favorites_heading"
    case favoritesBody = "favorites_body"
    case browseCharacters = "browse_characters"
    case charactersCount = "characters_count"
    case searchCharacters = "search_characters"
    case filterAll = "filter_all"
    case detailActionFavorite = "detail_action_favorite"
    case actionShare = "action_share"
    case shareCharacterText = "share_character_text"
    case detailStatEpisodes = "detail_stat_episodes"
    case detailStatDimension = "detail_stat_dimension"
    case detailStatSpecies = "detail_stat_species"
    case detailInfoOrigin = "detail_info_origin"
    case detailInfoLastKnownLocation = "detail_info_last_known_location"
    case detailInfoFirstSeenIn = "detail_info_first_seen_in"
    case settingsSectionPreferences = "settings_section_preferences"
    case settingsSectionData = "settings_section_data"
    case settingsSoundTitle = "settings_sound_title"
    case settingsSoundBody = "settings_sound_body"
    case settingsDataSourceTitle = "settings_data_source_title"
    case settingsDataSourceBody = "settings_data_source_body"
    case settingsDataRest = "settings_data_rest"
    case settingsDataGraphql = "settings_data_graphql"
    case settingsDeleteAction = "settings_delete_action"
    case settingsDeleteExplanation = "settings_delete_explanation"
    case settingsDeleteConfirmTitle = "settings_delete_confirm_title"
    case settingsDeleteConfirmMessage = "settings_delete_confirm_message"
    case actionCancel = "action_cancel"
    case actionDelete = "action_delete"
}
