// :core:testing — the shared test harness: fixtures, the FixtureLoader seam, the
// MockEngine harness and coroutine/time control helpers.
//
// Consumed from test source sets only; DESIGN.md §3.1 places it on `:core:domain` and
// `:core:data` (R5 of verifyModuleBoundaries, see CONF-39 for the ADR-0001 wording).
//
// Fixtures are committed under `src/commonMain/resources/fixtures/` as ordinary files with
// dated sidecars, so a reviewer diffs them like any other source (TESTING.md §4.3, §4.4).
// Kotlin Multiplatform has no portable runtime resource API, so the build embeds them into a
// generated Kotlin source instead of reading them from the filesystem: the same bytes reach
// Android, Kotlin/Native and any future target, and no test depends on a working directory.

plugins {
    id("multiverse.kmp.library")
}

val fixtureDirectory = layout.projectDirectory.dir("src/commonMain/resources/fixtures")
val generatedFixtureDirectory = layout.buildDirectory.dir("generated/fixtures/kotlin")

/**
 * Embeds the committed fixtures and their sidecars into one generated Kotlin object.
 *
 * The fixtures stay the source of truth and are read from disk only here; the generated file is
 * build output and is never committed. Escaping is explicit so a fixture body containing quotes,
 * backslashes or a `$` cannot corrupt the generated source.
 */
val generateFixtureSources =
    tasks.register("generateFixtureSources") {
        // `*.json` also matches `*.meta.json`, so the sidecars are excluded here and collected by
        // their own tree; the catalogue of fixture *names* must never list a sidecar.
        val fixtures =
            fileTree(fixtureDirectory) {
                include("*.json", "*.txt")
                exclude("*.meta.json")
            }
        val sidecars = fileTree(fixtureDirectory) { include("*.meta.json") }
        inputs.files(fixtures, sidecars).withPropertyName("fixtures")
        val output = generatedFixtureDirectory
        outputs.dir(output)

        doLast {
            val files = fixtures.files.sortedBy { it.name }
            val metaFiles = sidecars.files.sortedBy { it.name }
            val target =
                output
                    .get()
                    .asFile
                    .resolve("io/github/davidru85/multiverse/testing/GeneratedFixtures.kt")
            target.parentFile.mkdirs()

            fun escape(text: String) =
                buildString {
                    text.forEach { c ->
                        when (c) {
                            '\\' -> append("\\\\")
                            '"' -> append("\\\"")
                            '$' -> append("\${'$'}")
                            '\n' -> append("\\n")
                            '\r' -> append("\\r")
                            '\t' -> append("\\t")
                            else -> if (c.code < 0x20) append("\\u%04x".format(c.code)) else append(c)
                        }
                    }
                }

            target.writeText(
                buildString {
                    appendLine("// Generated by :core:testing:generateFixtureSources — do not edit.")
                    appendLine("// The committed fixtures under src/commonMain/resources/fixtures are the source of truth.")
                    appendLine("package io.github.davidru85.multiverse.testing")
                    appendLine()
                    appendLine("internal object GeneratedFixtures {")
                    appendLine("    val names: List<String> = listOf(")
                    files.forEach { appendLine("        \"${it.name}\",") }
                    appendLine("    )")
                    appendLine()
                    appendLine("    val contents: Map<String, String> = mapOf(")
                    files.forEach { file ->
                        appendLine("        \"${file.name}\" to \"${escape(file.readText())}\",")
                    }
                    metaFiles.forEach { file ->
                        appendLine("        \"${file.name}\" to \"${escape(file.readText())}\",")
                    }
                    appendLine("    )")
                    appendLine("}")
                },
            )
        }
    }

kotlin {
    sourceSets {
        commonMain {
            kotlin.srcDir(generateFixtureSources)
            dependencies {
                // The doubles implement and return `:core:domain` types, so the edge is part of the
                // harness's surface (`TASK-036`).
                api(project(":core:domain"))
                implementation(project(":core:data"))

                // The harness surface: virtual time and the MockEngine seam are the two
                // mechanisms TESTING.md §5 and §4.1 permit, and both are already pinned in
                // the catalog for this purpose (TASK-024).
                api(libs.kotlinx.coroutines.test)
                api(libs.ktor.client.mock)
                api(libs.ktor.client.core)
            }
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            // The harness exercises `:core:testing`'s own helpers, so the transitive test runtime
            // is declared where it is used (`onUsedTransitiveDependencies`, DEC-077).
            implementation(libs.kotlinx.coroutines.test)
        }
        jvmMain.dependencies {
            // The opt-in JVM target (`DEC-079`, `DEC-089`) is analysed on its own, and dependency
            // analysis asks for the domain edge to be stated for it as well.
            api(project(":core:domain"))
        }
        androidHostTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlin.test.junit)
            implementation(libs.kotlinx.coroutines.core)
        }
        androidMain.dependencies {
            // `MockHttp` binds `io.ktor.http` types directly, so the artifact is declared where
            // it is used rather than reached transitively (DEC-077). `ktor-client-core` is
            // already `api` from `commonMain` and must not be redeclared here.
            implementation(libs.ktor.http)
        }
    }
}
